[project]
name = 'deploy-cata'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.btc-stx-swap]
path = 'contracts/btc-stx-swap.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulate]
path = 'contracts/simulate.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
